---
- name: Clean previous deploy attempts
  hosts: localhost
  connection: local
  tasks:
  - name: Stop libvirt service
    service:
      name: libvirtd
      state: stopped
      enabled: yes
  - name: Drop vdsm config statements
    command: sed -i '/## beginning of configuration section by vdsm-4.[0-9]\+.[0-9]\+/,/## end of configuration section by vdsm-4.[0-9]\+.[0-9]\+/d' {{ item }}
    with_items:
      - /etc/libvirt/libvirtd.conf
      - /etc/libvirt/qemu.conf
      - /etc/libvirt/qemu-sanlock.conf
      - /etc/sysconfig/libvirtd
    tags: [ 'skip_ansible_lint' ]
  - name: Restore initial abrt config files
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
      - { src: /usr/share/abrt/conf.d/abrt-action-save-package-data.conf, dest: /etc/abrt/abrt-action-save-package-data.conf }
      - { src: /usr/share/abrt/conf.d/abrt.conf, dest: /etc/abrt/abrt.conf }
      - { src: /usr/share/abrt/conf.d/plugins/CCpp.conf, dest: /etc/abrt/plugins/CCpp.conf }
      - { src: /usr/share/abrt/conf.d/plugins/vmcore.conf, dest: /etc/abrt/plugins/vmcore.conf }
  - name: Restart abrtd service
    service:
      name: abrtd
      state: restarted
  - name: Drop libvirt sasl2 configuration by vdsm
    command: sed -i '/## start vdsm-4.[0-9]\+.[0-9]\+ configuration/,/## end vdsm configuration/d' /etc/sasl2/libvirt.conf
    tags: [ 'skip_ansible_lint' ]
  - name: Stop and disable services
    service:
      name: "{{ item }}"
      state: stopped
      enabled: no
    with_items:
      - ovirt-ha-agent
      - ovirt-ha-broker
      - vdsmd
  - name: Start libvirt
    service:
      name: libvirtd
      state: started
      enabled: yes
  - name: Check for leftover local Hosted Engine VM
    shell: virsh list | grep {{ VM_NAME }}Local | cat
    changed_when: True
    register: local_vm_list
  - name: Destroy leftover local Hosted Engine VM
    command: virsh destroy {{ VM_NAME }}Local
    ignore_errors: yes
    when: local_vm_list.stdout_lines|length >= 1
  - name: Check for leftover defined local Hosted Engine VM
    shell: virsh list --all | grep {{ VM_NAME }}Local | cat
    changed_when: True
    register: local_vm_list_all
  - name: Undefine leftover local engine VM
    command: virsh undefine --managed-save {{ VM_NAME }}Local
    when: local_vm_list_all.stdout_lines|length >= 1
    changed_when: True
  - name: Remove eventually entries for the local VM from known_hosts file
    known_hosts:
      name: "{{ FQDN }}"
      state: absent
...
