---
- name: iSCSI related tasks
  hosts: localhost
  connection: local
  tasks:
  - include_tasks: auth_sso.yml
  - name: iSCSI login
    ovirt_host:
      name: "{{ HOST_NAME }}"
      state: iscsilogin
      timeout: 30
      iscsi:
        username: "{{ ISCSI_USERNAME }}"
        password: "{{ ISCSI_PASSWORD }}"
        address: "{{ item.0 }}"
        port: "{{ item.1 }}"
        target: "{{ ISCSI_TARGET }}"
      auth: "{{ ovirt_auth }}"
    ignore_errors: yes
    # TODO: avoid the with_together loop once
    # https://github.com/ansible/ansible/issues/32640 got properly fixed
    with_together:
      - "{{ ISCSI_PORTAL_ADDR.split(',') }}"
      - "{{ ISCSI_PORTAL_PORT.split(',') if ISCSI_PORTAL_PORT is string else ISCSI_PORTAL_PORT }}"
  - name: Get iSCSI LUNs
    ovirt_host_storage_facts:
      host: "{{ HOST_NAME }}"
      iscsi:
        username: "{{ ISCSI_USERNAME }}"
        password: "{{ ISCSI_PASSWORD }}"
        address: "{{ ISCSI_PORTAL_ADDR.split(',')|first }}"
        port: "{{ ISCSI_PORTAL_PORT.split(',')|first if ISCSI_PORTAL_PORT is string else ISCSI_PORTAL_PORT }}"
        target: "{{ ISCSI_TARGET }}"
      auth: "{{ ovirt_auth }}"
    register: otopi_iscsi_devices
  - debug: var=otopi_iscsi_devices
...
